// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTuQKHP35i21-Xixrw3dO5n8wxXeUrUGk',
    appId: '1:449850753086:web:a3b9220bb0422ff193116f',
    messagingSenderId: '449850753086',
    projectId: 'droplet-8f602',
    authDomain: 'droplet-8f602.firebaseapp.com',
    storageBucket: 'droplet-8f602.firebasestorage.app',
    measurementId: 'G-8837Z2KLKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClXO7HNxgzMQ-QcffAgQ6LPZSk88rILF4',
    appId: '1:449850753086:android:ec689e7b4ff8177093116f',
    messagingSenderId: '449850753086',
    projectId: 'droplet-8f602',
    storageBucket: 'droplet-8f602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVUbrFOR0Q-jfM4UfczmZGo2pBtEjTVRo',
    appId: '1:449850753086:ios:772f63725cee6b3593116f',
    messagingSenderId: '449850753086',
    projectId: 'droplet-8f602',
    storageBucket: 'droplet-8f602.firebasestorage.app',
    iosBundleId: 'com.example.droplet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVUbrFOR0Q-jfM4UfczmZGo2pBtEjTVRo',
    appId: '1:449850753086:ios:772f63725cee6b3593116f',
    messagingSenderId: '449850753086',
    projectId: 'droplet-8f602',
    storageBucket: 'droplet-8f602.firebasestorage.app',
    iosBundleId: 'com.example.droplet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTuQKHP35i21-Xixrw3dO5n8wxXeUrUGk',
    appId: '1:449850753086:web:10886337a9437f0493116f',
    messagingSenderId: '449850753086',
    projectId: 'droplet-8f602',
    authDomain: 'droplet-8f602.firebaseapp.com',
    storageBucket: 'droplet-8f602.firebasestorage.app',
    measurementId: 'G-XLG7W44Z1H',
  );
}
